version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tgpostgreDB
      POSTGRES_USER: tgadmin
      POSTGRES_PASSWORD: tgadmin1!
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    command: >
      postgres
      -c listen_addresses='*'
      -c max_connections=200
      -c shared_buffers=256MB
      -c log_statement=all
      -c log_destination=stderr
    ports:
      - "35432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tgadmin -d tgpostgreDB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local